python:
  - 3.12.9

numpy:
  - 2.3.2

boost:
  - 1.84.0

pybind11:
  - 2.13.6

volk:
  - 3.1.2

gnuradio_core:
  - 3.10.11.0

zip_keys:
  - python
  - numpy
  - boost
  - pybind11
  - volk
  - gnuradio_core
