
package:
  name:  limesuiteng
  version: 25.1.0

source:
  path: "../.."

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - git
    - ninja
    - pkg-config
    - python =3.12.9                    
    - numpy                             
    - vs2022_win-64

  host:
    - pip
    - python =3.12.9
    - numpy

  run:
    - numpy
    - python =3.12.9

test:
  commands:
    - if not exist %PREFIX%\\Library\\include\\lime\\LimeSuite.h exit 1
    - if not exist %PREFIX%\\Library\\include\\lime\\LMS7002M_parameters.h exit 1

    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\complex.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\config.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\CSRegister.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\DeviceHandle.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\DeviceRegistry.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\LimePlugin.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\limesuiteng.hpp exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\LMS7002M.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\LMS7002MCSR.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\Logger.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\OpStatus.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\Register.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\RFSOCDescriptor.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\RFStream.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\SDRConfig.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\SDRDescriptor.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\SDRDevice.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\StreamConfig.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\ToString.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\types.h exit 1
    - if not exist %PREFIX%\\Library\\include\\limesuiteng\\VersionInfo.h exit 1

    - if not exist %PREFIX%\\Library\\bin\\limeConfig.exe exit 1
    - if not exist %PREFIX%\\Library\\bin\\limeDevice.exe exit 1
    - if not exist %PREFIX%\\Library\\bin\\limeFLASH.exe exit 1
    - if not exist %PREFIX%\\Library\\bin\\wxmsw32u_gl_vc14x_x64.dll exit 1
    - if not exist %PREFIX%\\Library\\bin\\wxmsw32u_core_vc14x_x64.dll exit 1
    - if not exist %PREFIX%\\Library\\bin\\wxbase32u_vc14x_x64.dll exit 1
    - if not exist %PREFIX%\\Library\\bin\\limeGUI.exe exit 1
    - if not exist %PREFIX%\\Library\\bin\\limeOEM.exe exit 1
    - if not exist %PREFIX%\\Library\\bin\\limeSPI.exe exit 1
    - if not exist %PREFIX%\\Library\\bin\\limeTRX.exe exit 1
    - if not exist %PREFIX%\\Library\\bin\\limesuiteng.dll exit 1 

    - if not exist %PREFIX%\\Library\\lib\\limesuiteng.lib exit 1
    - if not exist %PREFIX%\\Library\\lib\\limesuiteng-legacyapi.lib exit 1
    - if not exist %PREFIX%\\Library\\lib\\limesuiteng-legacyapi.dll exit 1
    - if not exist %PREFIX%\\Library\\lib\\pkgconfig\\limesuiteng.pc exit 1
    - if not exist %PREFIX%\\Library\\lib\\cmake\\limesuiteng\\limesuitengConfigVersion.cmake exit 1
    - if not exist %PREFIX%\\Library\\lib\\cmake\\limesuiteng\\limesuitengTargets.cmake exit 1
    - if not exist %PREFIX%\\Library\\lib\\cmake\\limesuiteng\\limesuitengTargets-release.cmake exit 1
    - if not exist %PREFIX%\\Library\\lib\\cmake\\limesuiteng\\limesuitengConfig.cmake exit 1

about:
  home: https://github.com/myriadrf/LimeSuiteNG
  license: Apache-2.0
  license_file: COPYING
  license_url: https://github.com/myriadrf/LimeSuiteNG?tab=Apache-2.0-1-ov-file#readme
  summary: Lime Suite NG is a new generation software suite designed for working with LimeSDR family devices.
  dev_url: https://github.com/myriadrf/LimeSuiteNG
  doc_url: https://limesuiteng.myriadrf.org/
