#ifndef __fftviewer_frFFTviewer__
#define __fftviewer_frFFTviewer__

/**
@file
Subclass of frFFTviewer, which is generated by wxFormBuilder.
*/
#include <thread>
#include <atomic>
#include <vector>
#include <array>
#include "fftviewer_wxgui.h"
#include <wx/timer.h>
#include <mutex>
#include <condition_variable>
#include <filesystem>

namespace lime {
class SDRDevice;
}

class fftviewer_frFFTviewer : public frFFTviewer
{
  public:
    bool Initialize(lime::SDRDevice* device) override;
    void Update() override;

  protected:
    std::atomic<int> windowFunctionID{};
    std::atomic<bool> captureSamples{};
    std::atomic<int> averageCount{};
    std::atomic<bool> updateGUI{};
    std::atomic<bool> enableFFT{};
    std::filesystem::path captureFilename;
    // Handlers for frFFTviewer events.
    void OnWindowFunctionChanged(wxCommandEvent& event);
    void OnbtnStartStop(wxCommandEvent& event) override;
    void OnChannelVisibilityChange(wxCommandEvent& event) override;
    void OnStreamChange(wxCommandEvent& event) override;
    void OnEnPwr(wxCommandEvent& event) override;
    void OnFmtChange(wxCommandEvent& event) override;
    void OnAvgChange(wxSpinEvent& event) override;
    void OnAvgChangeEnter(wxCommandEvent& event) override;
    void OnWindowFunctionChange(wxCommandEvent& event) override;
    bool Show(bool show) override;
    static void StreamingLoop(
        fftviewer_frFFTviewer* pthis, const unsigned int fftSize, const uint8_t channelEnablesMask, const uint32_t format);

    void OnUpdateStats(wxTimerEvent& event);
    void OnUpdatePlots(wxThreadEvent& event);

  public:
    /** Constructor */
    fftviewer_frFFTviewer(wxWindow* parent, wxWindowID id);
    ~fftviewer_frFFTviewer();
    //// end generated class members
    void SetNyquistFrequency();

    void StartStreaming();
    void StopStreaming();
    void OnbtnCaptureClick(wxCommandEvent& event);

  protected:
    static constexpr uint8_t cMaxChCount = 2;

    /** @brief Structure for storing the fast Fourier transform information for the display into the GUI */
    struct DataToGUI {
        std::array<std::vector<float>, cMaxChCount> samplesI; ///< The in-phase component samples
        std::array<std::vector<float>, cMaxChCount> samplesQ; ///< The quadrature component samples
        std::array<std::vector<float>, cMaxChCount> fftBins; ///< The fast Fourier transform bins
        float nyquist_Hz; ///< The Nyquist frequency
        float rxDataRate_Bps; ///< The input data speed, in bytes per second
        float txDataRate_Bps; ///< The output data speed, in bytes per second

        std::mutex mutex;
        std::atomic<bool> isDataReady;
        std::condition_variable cv;

        /**
          @brief The copy operator of the class.
          @param src The instance to copy the data from.
          @return The new instance of this class.
         */
        DataToGUI& operator=(DataToGUI& src)
        {
            for (int ch = 0; ch < cMaxChCount; ++ch)
            {
                samplesI[ch].swap(src.samplesI[ch]);
                samplesQ[ch].swap(src.samplesQ[ch]);
                fftBins[ch].swap(src.fftBins[ch]);
                nyquist_Hz = src.nyquist_Hz;
                rxDataRate_Bps = src.rxDataRate_Bps;
                txDataRate_Bps = src.txDataRate_Bps;
                src.isDataReady.store(false);
            }
            return *this;
        }
    } streamData;

    std::vector<float> fftFreqAxis;
    std::vector<float> timeXAxis;
    std::atomic<bool> mStreamRunning;
    std::atomic<bool> stopProcessing{};
    std::thread threadProcessing;
    wxString printDataRate(float dataRate);

    lime::SDRDevice* device;
    wxTimer* mGUIupdater;
    unsigned lmsIndex{};
};

#endif // __fftviewer_frFFTviewer__
