function(REMOVE_MODULE MODULE_NAME ERROR_SEVERITY)
    execute_process(COMMAND bash "-c" "lsmod | grep -E '^${MODULE_NAME}\\b'"  OUTPUT_VARIABLE MODULE_INFO)
    if(NOT MODULE_INFO)
        return()
    endif()

    message(STATUS "Removing module: ${MODULE_NAME}")
    execute_process(COMMAND bash "-c" "echo '${MODULE_INFO}' | grep -Eq ' 0$'"  RESULT_VARIABLE IS_USED)
    if(IS_USED)
        message(${ERROR_SEVERITY} "Could not remove ${MODULE_NAME}: It is being used!")
    else()
        execute_process(COMMAND bash "-c" "rmmod ${MODULE_NAME}")
    endif()
endfunction()

execute_process(COMMAND bash "-c" "id -u" OUTPUT_VARIABLE USER_ID)
if(NOT ${USER_ID} EQUAL "0")
    message(FATAL_ERROR "Installation requires root permissions!")
endif()

execute_process(COMMAND bash "-c" "lsmod | grep -E '^litepcie\\b'"  OUTPUT_VARIABLE LEGACY_MODULE_FOUND)
if(LEGACY_MODULE_FOUND)
    message(STATUS "Detected legacy module: litepcie")
    remove_module("litepcie" WARNING)
    execute_process(COMMAND bash "-c" "lsmod | grep -E '^litepcie\\b'"  OUTPUT_VARIABLE LEGACY_MODULE_FOUND)
    if(LEGACY_MODULE_FOUND)
        message(WARNING "Could not remove litepcie. Manualy remove it and reinstall driver or reboot device to finalize installation")
    endif()
endif()
execute_process(COMMAND bash "-c" "sed -i '/^litepcie$/d' /etc/modules")

remove_module("limelitepcie" FATAL_ERROR)
