.. These are replacement strings for non-ASCII characters used within the
   project, using the same name as the HTML entity names (e.g., &copy;).

.. |graph_note| replace:: You can zoom and move around the diagram using the mouse.
