name: cmake-format

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq cmake-format

      - name: Run cmake-format
        run: |
          cmake-format --check $(find ${{github.workspace}} -name CMakeLists.txt)
          code=$?
          if [[ $code != 0 ]]; then
              exit 1
          fi
          exit 0
